### ISSUE TITLE
How to use other sqm?

### ISSUE THREAD

**Issue by KubaAseph** [stg/Squawk#2]
How to insert other code than The Original? I tried both my .mod and those included (of course converted to .sqm).
I can't load them to sketch editor, if I open them I got lots of "NUL" symbols with only some "xXX" on any symbol coding system, and I haven't found anything like filepatch in code.
HOW TO EXTRACT THE DAMNED CODE?!

**Comment by stg** [comment]
Watch your language, buddy.

When converting you get the option to convert the mod file into either an .sqm file or a .c file.
If you are using Windows you will get this choice as a "Save File"-dialog:

Squawk module (sqm) will produce an .sqm file for SD-cards
Squawk c-array (c/cpp/txt) will produce c-code - a byte array suitable for insertion into code.
