### ISSUE TITLE
Issue comiling the squawk player code

### ISSUE THREAD

**Issue by 8bit-coder** [stg/Squawk#4]
I tried to compile the squawk player code with arduino IDE version 1.6.11 and I got these:

```
In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28:0,

                 from C:\Program Files (x86)\Arduino\libraries\Squawk\Squawk.h:10,

                 from C:\Program Files (x86)\Arduino\libraries\Squawk\Squawk.cpp:6:

C:\Program Files (x86)\Arduino\libraries\Squawk\Squawk.cpp:85:25: error: variable 'period_tbl' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 uint16_t period_tbl[84] PROGMEM = {

                         ^

C:\Program Files (x86)\Arduino\libraries\Squawk\Squawk.cpp:96:21: error: variable 'sine_tbl' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

 int8_t sine_tbl[32] PROGMEM = {

                     ^

Multiple libraries were found for "Squawk.h"
 Used: C:\Program Files (x86)\Arduino\libraries\Squawk
 Not used: C:\Program Files (x86)\Arduino\libraries\Robot_Control
exit status 1
Error compiling for board Arduino/Genuino Uno.

```

**Comment by TheAnimeAnimator** [comment]
Nevermind that, I put const in front of the variables and now those errors are gone, and now these ones took their place:
```

`pcm' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Squawk\Squawk.cpp.o (symbol from plugin)

`cia_count' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of sketch\Squawk_player.ino.cpp.o (symbol from plugin)

`cia_count' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of sketch\Squawk_player.ino.cpp.o (symbol from plugin)

`cia_count' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of sketch\Squawk_player.ino.cpp.o (symbol from plugin)

`cia_count' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of sketch\Squawk_player.ino.cpp.o (symbol from plugin)

`cia_count' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of sketch\Squawk_player.ino.cpp.o (symbol from plugin)

`cia_count' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of sketch\Squawk_player.ino.cpp.o (symbol from plugin)

`squawk_playroutine' referenced in section `.text' of C:\Users\Parisa\AppData\Local\Temp\cc10UJ4U.ltrans0.ltrans.o: defined in discarded section `.text' of libraries\Squawk\Squawk.cpp.o (symbol from plugin)

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "Squawk.h"
 Used: C:\Program Files (x86)\Arduino\libraries\Squawk
 Not used: C:\Program Files (x86)\Arduino\libraries\Robot_Control
exit status 1
Error compiling for board Arduino/Genuino Uno.
```

Yeah  . . . I don't know how to fix that

**Comment by JO3RI** [comment]
squawk library is part of the "Robot Control" too, so the IDE doesn't know which one to pick. You could move one out of the Arduino library folder for testing.

**Comment by vjail** [comment]
Hi, I have a problem compiling squawk in arduino 1.8.8, in 1.0.5 no problem. this is the errors:

C:\Users\vjail\AppData\Local\Temp\ccBVA9k9.ltrans0.ltrans.o: In function `__vector_11':

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `osc'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `osc'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `osc'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `osc'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `osc'

C:\Users\vjail\AppData\Local\Temp\ccBVA9k9.ltrans0.ltrans.o:D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: more undefined references to `osc' follow

C:\Users\vjail\AppData\Local\Temp\ccBVA9k9.ltrans0.ltrans.o: In function `__vector_11':

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `pcm'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia_count'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia_count'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia_count'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia_count'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia_count'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `cia_count'

D:\Arduino\Squawk-master\sketches\Squawk_player/Squawk_player.ino:26: undefined reference to `squawk_playroutine'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compilando para la tarjeta Arduino/Genuino Uno.

**Comment by stg** [comment]
I have updated the code for compatibility with Arduino IDE 1.8.8
