### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by shiyouganai** [stg/Squawk#5]
Hello,

First, I want to thank the author/contributors for a very cool library.

I am looking to include a version of this library that I have modified to work on the Arduboy in a game I am releasing soon. I know that you worked on a pared down version for that platform, ATMlib, but I chose this original version as a base due to its .mod file support. I am aware of the large ROM usage, and have worked around it. Since I did not see a license in the repository, I wanted to open a request here: may I release software with a modified version of this library for non-commercial purposes?

If so, please let me know what attribution rules you would like and what notices, if any, I should include.

Thank you for your consideration!

**Comment by stg** [comment]
Yes, you have my permission to release software with a modifified version of this library under any license you prefer. Use your own moral compass to make a decision on attribution.
